---
title: "FindBaroData"
author: "Kriddie"
date: "2022-08-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(plotly)
library(here)
```

## Description

The purpose of this script is to identify the airpresser, air temp, water level and water temp at the time of sampling each wetland 

#read in data for Baro

```{r Read in Data}
BaroData <- read.csv(here::here("Wetlands/Wetland_Baro.csv"), skip=0, header = TRUE)
BaroData <- BaroData[,2:4]

BaroData$DateTime <- as.POSIXct(BaroData$DateTime, format="%Y-%m-%d %H:%M:%S", tz = "UTC")


```

## Check Data

#Plot all data



```{r Check Data, echo=FALSE}
ggplot(BaroData, aes(x=DateTime, y=AirPres_kpa)) +
    geom_point(size=2, shape=23)
ggplot(BaroData, aes(x=DateTime, y=AirTemp_c)) +
    geom_point(size=2, shape=23,color="blue")

```
## Check Data

#Plot all data


```{r Check sample day, echo=FALSE}
#enter date of collection
date_Start <- "2022-06-28"
date_END <- "2022-06-28"

ggplot(BaroData %>%
  filter(DateTime > as.POSIXct(paste(date_Start,"00:00:01"), format="%Y-%m-%d %H:%M:%S", tz = "UTC"))%>%
  filter(DateTime < as.POSIXct(paste(date_END,"23:59:59"), format="%Y-%m-%d %H:%M:%S", tz = "UTC")),
       aes(x=DateTime, y=AirPres_kpa)) +
  geom_point(size=2, shape=23)


ggplot(BaroData %>%
  filter(DateTime > as.POSIXct(paste(date_Start,"00:00:01"), format="%Y-%m-%d %H:%M:%S", tz = "UTC"))%>%
  filter(DateTime < as.POSIXct(paste(date_END,"23:59:59"), format="%Y-%m-%d %H:%M:%S", tz = "UTC")),
       aes(x=DateTime, y=AirTemp_c)) +
  geom_point(size=2, shape=23, color="blue")

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r select time, echo=FALSE}
#enter date of collection
date <- "2022-07-14"
#enter start and end time that wetland was sampled
time_START <- "10:16:00"
time_END <- "10:48:00"

#AirPressure

plot_ly(data=BaroData %>%
  filter(DateTime > as.POSIXct(paste(date,time_START), format="%Y-%m-%d %H:%M:%S", tz = "UTC"))%>%
  filter(DateTime < as.POSIXct(paste(date,time_END), format="%Y-%m-%d %H:%M:%S", tz = "UTC")),
  x=~DateTime,y=~AirPres_kpa)

#AirTemp

plot_ly(data=BaroData %>%
  filter(DateTime > as.POSIXct(paste(date,time_START), format="%Y-%m-%d %H:%M:%S", tz = "UTC"))%>%
  filter(DateTime < as.POSIXct(paste(date,time_END), format="%Y-%m-%d %H:%M:%S", tz = "UTC")),
  x=~DateTime,y=~AirTemp_c)

```

#summariz

```{r summarize, echo=FALSE}
#enter date of collection
date <- "2022-07-14"
#enter start and end time that wetland was sampled
time_START <- "10:47:00"
time_END <- "10:48:00"

ave <- BaroData%>%
  filter(DateTime > as.POSIXct(paste(date, time_START), format="%Y-%m-%d %H:%M:%S", tz = "UTC"))%>%
  filter(DateTime < as.POSIXct(paste(date, time_END), format="%Y-%m-%d %H:%M:%S", tz = "UTC"))%>%
  summarize(AirPres_mean = mean(AirPres_kpa),
            AirTemp_mean = mean(AirTemp_c))

print(ave)
```